### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by mrsharanya** [computervisiondeveloper/face-attendance-system#8]
User Registered Successfully
But
When Login and Logout 
following error is received

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "main.py", line 61, in login
    label = test(
TypeError: 'module' object is not callable

**Comment by mrsharanya** [comment]
In initial run when we faced error
 cannot import name 'test' from 'test' 

As mentioned from Issue #6 
we Modified 
from test import test  to impor test
